---
- name: Connect Master and Slave
  hosts: master
  gather_facts: no
  tasks:
    - name: Ensure SSH key is copied to slave
      ansible.builtin.copy:
        src: "/home/ubuntu/Concepts/PranayAWS.pem"
        dest: "/home/ubuntu/.ssh/id_rsa"
        mode: '0600'

    - name: Add the slave to known_hosts file on master
      ansible.builtin.shell:
        cmd: ssh-keyscan -H 13.203.103.154 >> /home/ubuntu/.ssh/known_hosts
        creates: /home/ubuntu/.ssh/known_hosts

    - name: Ensure that the slave is reachable from the master
      ansible.builtin.ping:
        delegate_to: 13.203.103.154

- name: Run a task on the slave
  hosts: slave
  gather_facts: yes
  tasks:
    - name: Ensure SSH key is present on the slave for master access
      ansible.builtin.copy:
        src: "/home/ubuntu/Concepts/PranayAWS.pem"
        dest: "/home/ubuntu/.ssh/authorized_keys"
        mode: '0600'

    - name: Check connection to master from slave
      ansible.builtin.ping:



- name: Install Java on Slave Instance
  hosts: slave
  become: yes  # Run tasks with sudo privileges
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java (OpenJDK 17)
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Verify Java Installation
      command: java -version
      register: java_version
      ignore_errors: yes

    - name: Display Java Version
      debug:
        msg: "{{ java_version.stdout }}"